hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/bills/**
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposits/**

server:
  port: 8989
#zuul:
#  ignoredServices: '*'
#  host:
#    connect-timeout-millis: 20000
#    socket-timeout-millis: 20000
#
#  routes:
#    account-service:
#      path: /accounts/**
#      serviceId: account-service
#      stripPrefix: false
#
#    bill-service:
#      path: /bills/**
#      serviceId: bill-service
#      stripPrefix: false
#
#    deposit-service:
#      path: /deposits/**
#      serviceId: deposit-service
#      stripPrefix: false
#